import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "./(protected)/components/layout/Header";
import Footer from "./(protected)/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mizzle",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.PNG',

  },
};

export default function PublicLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="d-flex flex-column min-vh-100">
        
        {children}
        
      </body>
    </html>
  );
}
